---
- id: ossindex:pypi:urllib3:CVE-2016-9015
  title: "[CVE-2016-9015] Versions 1.17 and 1.18 of the Python urllib3 library suffer
    from a vulnerability..."
  description: Versions 1.17 and 1.18 of the Python urllib3 library suffer from a
    vulnerability that can cause them, in certain configurations, to not correctly
    validate TLS certificates. This places users of the library with those configurations
    at risk of man-in-the-middle and information leakage attacks. This vulnerability
    affects users using versions 1.17 and 1.18 of the urllib3 library, who are using
    the optional PyOpenSSL support for TLS instead of the regular standard library
    TLS backend, and who are using OpenSSL 1.1.0 via PyOpenSSL. This is an extremely
    uncommon configuration, so the security impact of this vulnerability is low.
  affected_package: urllib3
  vulnerable_versions:
  - '1.17'
  - '1.18'
  package_manager: pypi
  cve:
  - CVE-2016-9015
  disclosed_date: 2017-01-11
  created_date: 2017-01-11
  last_modified_date: 2017-01-13
  credit:
  - OSSIndex
  references:
  - http://www.openwall.com/lists/oss-security/2016/10/27/6
  - http://www.securityfocus.com/bid/93941
  source_url: https://ossindex.net/resource/package/8401376142/vulnerabilities
- id: snykio:pypi:urllib3:CVE-2016-9015
  title: Improper Certificate Validation
  description: |
    [`urllib3`][1] is a HTTP library with thread-safe connection pooling,
    file post, and more.

    Affected versions of this package fail to validate TSL certificates in
    certain configurations. This places users of the library with those
    configurations at risk of man-in-the-middle and information leakage
    attacks. This vulnerability affects users using versions 1.17 and 1.18
    of the urllib3 library, who are using the optional PyOpenSSL support for
    TLS instead of the regular standard library TLS backend, and who are
    using OpenSSL 1.1.0 via PyOpenSSL. This is an extremely uncommon
    configuration, so the security impact of this vulnerability is low.



    [1]: https://pypi.python.org/pypi/urllib3
  affected_package: urllib3
  vulnerable_versions:
  - ">= 1.17 < 1.18.1"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2016-9015
  cwe:
  - CWE-295
  disclosed_date: 2016-10-27
  created_date: 2016-10-27
  last_modified_date: 2016-10-27
  credit:
  - Cory Benfield
  references:
  - https://github.com/shazow/urllib3/commit/5e36a7096455ea94fb28b623d64e1f1bad97f822
  - https://github.com/shazow/urllib3/pull/1010
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-9015
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-40441
