---
- id: ossindex:pypi:urllib3:8402343062
  title: "[CVE-2016-9015] Versions 1.17 and 1.18 of the Python urllib3 library suffer
    from a vulnerability..."
  description: Versions 1.17 and 1.18 of the Python urllib3 library suffer from a
    vulnerability that can cause them, in certain configurations, to not correctly
    validate TLS certificates. This places users of the library with those configurations
    at risk of man-in-the-middle and information leakage attacks. This vulnerability
    affects users using versions 1.17 and 1.18 of the urllib3 library, who are using
    the optional PyOpenSSL support for TLS instead of the regular standard library
    TLS backend, and who are using OpenSSL 1.1.0 via PyOpenSSL. This is an extremely
    uncommon configuration, so the security impact of this vulnerability is low.
  affected_package: urllib3
  vulnerable_versions:
  - '1.17'
  - '1.18'
  package_manager: pypi
  cve:
  - CVE-2016-9015
  disclosed_date: 2017-01-11
  created_date: 2017-01-11
  last_modified_date: 2017-01-13
  credit:
  - OSSIndex
  references:
  - http://www.openwall.com/lists/oss-security/2016/10/27/6
  - http://www.securityfocus.com/bid/93941
  source_url: https://ossindex.net/resource/package/8401376142/vulnerabilities
- id: snykio:pypi:urllib3:174323
  title: CRLF injection
  description: |
    [urllib3][1] is an HTTP library with thread-safe connection pooling,
    file post, and more.

    Affected versions of this package are vulnerable to CRLF injection.
    Attacker who has the control of the requesting address parameter, could
    manipulate an HTTP header and attack an internal service.



    [1]: https://pypi.org/project/urllib3/
  affected_package: urllib3
  vulnerable_versions:
  - ">= 1.24.1"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2019-11236
  cwe:
  - CWE-93
  disclosed_date: 2019-04-15
  created_date: 2019-04-18
  last_modified_date: 2019-04-18
  credit:
  - Unknown
  references:
  - https://github.com/urllib3/urllib3/issues/1553
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323
- id: snykio:pypi:urllib3:40441
  title: Improper Certificate Validation
  description: |
    [`urllib3`][1] is a HTTP library with thread-safe connection pooling,
    file post, and more.

    Affected versions of this package fail to validate TSL certificates in
    certain configurations. This places users of the library with those
    configurations at risk of man-in-the-middle and information leakage
    attacks. This vulnerability affects users using versions 1.17 and 1.18
    of the urllib3 library, who are using the optional PyOpenSSL support for
    TLS instead of the regular standard library TLS backend, and who are
    using OpenSSL 1.1.0 via PyOpenSSL. This is an extremely uncommon
    configuration, so the security impact of this vulnerability is low.



    [1]: https://pypi.python.org/pypi/urllib3
  affected_package: urllib3
  vulnerable_versions:
  - ">= 1.17 < 1.18.1"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2016-9015
  cwe:
  - CWE-295
  disclosed_date: 2016-10-27
  created_date: 2016-10-27
  last_modified_date: 2016-10-27
  credit:
  - Cory Benfield
  references:
  - https://github.com/shazow/urllib3/commit/5e36a7096455ea94fb28b623d64e1f1bad97f822
  - https://github.com/shazow/urllib3/pull/1010
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-9015
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-40441
- id: snykio:pypi:urllib3:72681
  title: Authentication Bypass
  description: |
    [urllib3][1] is a HTTP library with thread-safe connection pooling, file
    post, and more.

    Affected versions of this package are vulnerable to Authentication
    Bypass. It did remove the Authorization HTTP header when following a
    cross-origin redirect. This can allow for credentials in the
    Authorization header to be exposed to unintended hosts or transmitted in
    cleartext.



    [1]: https://pypi.org/project/urllib3/
  affected_package: urllib3
  vulnerable_versions:
  - "< 1.23"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2018-20060
  cwe:
  - CWE-288
  disclosed_date: 2018-12-11
  created_date: 2018-12-12
  last_modified_date: 2018-12-12
  credit:
  - Unknown
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=1649153
  - https://github.com/urllib3/urllib3/issues/1316
  - https://github.com/urllib3/urllib3/pull/1346
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-72681
